<a href="https://colab.research.google.com/github/ShenlyR/Analisis-Numerik/blob/main/Volume%20Lambung%20Kapal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import Library**

In [ ]:
import numpy as np
import pandas as pd
from scipy.integrate import simpson, trapezoid

ImportError: cannot import name 'image' from 'PIL' (/usr/local/lib/python3.13/dist-packages/PIL/__init__.py)

**Grid Tampak Atas**

In [ ]:
ukuran_dash = 5
ukuran_celah = 5

# satu kotak interval
jumlah_dash_atas = 5
jumlah_celah_atas = 4

interval_cm_atas = (jumlah_dash_atas * ukuran_dash) + (jumlah_celah_atas * ukuran_celah)
interval_m_atas = interval_cm / 100

print("Ukuran 1 interval:", interval_cm_atas, "cm")
print("Ukuran 1 interval:", interval_m_atas, "m")

Ukuran 1 interval: 45 cm
Ukuran 1 interval: 0.45 m

**Interval Tampak Atas**

In [ ]:
jumlah_interval_atas = 16
panjang_kapal_atas = jumlah_interval_atas * interval_m_atas

print("Jumlah interval:", jumlah_interval_atas)
print("Panjang tampak atas:", panjang_kapal_atas)

Jumlah interval: 16
Panjang tampak atas: 7.2

In [ ]:
titik_atas = np.arange(jumlah_interval_atas + 1)
jarak_atas = titik_atas * interval_m_atas

hasil_tampak_atas = pd.DataFrame({
    "Titik": titik_atas,
    "Jarak(m)": jarak_atas
})

hasil_tampak_atas["Jarak(m)"] = hasil_tampak_atas["Jarak(m)"].round(2)
hasil_tampak_atas

    Titik  Jarak(m)
0       0      0.00
1       1      0.45
2       2      0.90
3       3      1.35
4       4      1.80
5       5      2.25
6       6      2.70
7       7      3.15
8       8      3.60
9       9      4.05
10     10      4.50
11     11      4.95
12     12      5.40
13     13      5.85
14     14      6.30
15     15      6.75
16     16      7.20

**Grid Tampak Samping**

In [ ]:
ukuran_dash = 5
ukuran_celah = 5

jumlah_dash_samping = 5
jumlah_celah_samping = 5

interval_samping_cm = (jumlah_dash_samping * ukuran_dash) + (jumlah_celah_samping * ukuran_celah)
interval_samping_m = interval_samping_cm / 100

print("Ukuran 1 interval:", interval_samping_cm, "cm")
print("Ukuran 1 interval:", interval_samping_m, "m")

Ukuran 1 interval: 50 cm
Ukuran 1 interval: 0.5 m

**Interval Tampak Samping**

In [ ]:
jumlah_interval_samping = 20
panjang_samping = jumlah_interval_samping * interval_samping_m

print("Jumlah interval:", jumlah_interval_samping)
print("Panjang tampak samping:", panjang_samping, "m")

Jumlah interval: 20
Panjang tampak samping: 10.0 m

In [ ]:
titik_samping = np.arange(jumlah_interval_samping + 1)
jarak_samping = titik_samping * interval_samping_m

hasil_tampak_samping = pd.DataFrame({
    "Titik": titik_samping,
    "Jarak(m)": jarak_samping
})

hasil_tampak_samping["Jarak(m)"] = hasil_tampak_samping["Jarak(m)"].round(2)
hasil_tampak_samping

    Titik  Jarak(m)
0       0       0.0
1       1       0.5
2       2       1.0
3       3       1.5
4       4       2.0
5       5       2.5
6       6       3.0
7       7       3.5
8       8       4.0
9       9       4.5
10     10       5.0
11     11       5.5
12     12       6.0
13     13       6.5
14     14       7.0
15     15       7.5
16     16       8.0
17     17       8.5
18     18       9.0
19     19       9.5
20     20      10.0

**Tinggi Lambung Kapal**

In [ ]:
jumlah_dash_tinggi = 11
jumlah_celah_tinggi = 10

tinggi_cm = (jumlah_dash_tinggi * ukuran_dash) + (jumlah_celah_tinggi * ukuran_celah)
tinggi_m = tinggi_cm / 100

print("Tinggi:", tinggi_cm, "cm")
print("Tinggi:", tinggi_m, "m")

Tinggi: 105 cm
Tinggi: 1.05 m

**Titik Tinggi Lambung**

In [ ]:
jumlah_titik = 21

titik = np.arange(1, jumlah_titik + 1)
tinggi = np.full(jumlah_titik, tinggi_m)

hasil_tinggi = pd.DataFrame({
    "Titik": titik,
    "Tinggi(m)": tinggi
})

hasil_tinggi["Tinggi(m)"] = hasil_tinggi["Tinggi(m)"].round(2)
hasil_tinggi

    Titik  Tinggi(m)
0       1       1.05
1       2       1.05
2       3       1.05
3       4       1.05
4       5       1.05
5       6       1.05
6       7       1.05
7       8       1.05
8       9       1.05
9      10       1.05
10     11       1.05
11     12       1.05
12     13       1.05
13     14       1.05
14     15       1.05
15     16       1.05
16     17       1.05
17     18       1.05
18     19       1.05
19     20       1.05
20     21       1.05